-- =========================================================
-- Arku Remote — web sitesi yorumları
-- Tarih: 2026-08-02
-- DURUM: ⛔ GERİ ALINDI — yorumlar Supabase'de DEĞİL, Firestore'da tutuluyor.
--
-- Neden taşındı: Nexus CRM, Arku verisini Firestore'dan okuyor
-- (Pazarlama → Arku paneli `arku_events` koleksiyonunu dinliyor,
--  Firestore kuralları `allow read, write: if isOwner()`).
-- Yorumları Supabase'de tutmak, moderasyonun yapılacağı yerden kopuk
-- ikinci bir kaynak yaratıyordu.
--
-- YENİ AKIŞ:
--   Site formu → POST /api/reviews → Firebase Admin → Firestore `arku_reviews`
--   Site listesi → GET  /api/reviews → yalnızca status='approved' kayıtlar
--   Moderasyon  → Nexus CRM → Pazarlama → Arku → Yorumlar sekmesi
--
-- Kod: website/api/reviews.js
-- Firestore kuralı: nexus-crm/firestore.rules → match /arku_reviews/{id}
--
-- Bu dosyada bir zamanlar `arku_reviews` tablosu + `arku_public_reviews`
-- görünümü vardı; 20260802 tarihli drop migration'ı ile kaldırıldılar.
-- Tablo hiç üretim verisi almadı (yalnızca silinen test kayıtları).
-- Dosya, kararın izini bırakmak için korunuyor.
-- =========================================================

-- Uygulanan temizlik:
--   drop view  if exists public.arku_public_reviews;
--   drop table if exists public.arku_reviews;
